### ISSUE TITLE
Visual Studio Throws System.Reflection.TargetInvocationException Randomly

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/ProjectReunion#583]
**Describe the bug**

Visual Studio Throws System.Reflection.TargetInvocationException Randomly with Project Reunion App

**Steps to reproduce the bug**

1. Create New WinUI 3 Desktop Project
2. Run the App in Debug x86

**Expected behavior**

App should install all the required dll and run when debugging

**Screenshots**

![Screenshot 2021-03-13 170553](https://user-images.githubusercontent.com/17165402/111028792-f210ba80-841e-11eb-9c8a-a8769a5f6d4e.png)

**Version Info**

Windows 10 20H2 19042.867

NuGet package version: 

Microsoft.ProjectReunion 0.5.0.37570840

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by s3nt1n3l-hub** [comment]
Same issue here (same versions) - but with existing WinUI3 project updated to latest Reunion preview. No longer able to run the project at all due to 'Class not registered' error; For us though it's not random - its persistent.

**Comment by DefaultRyan** [comment]
Is this for a C++ or C# project?

**Comment by SoloWharf** [comment]
C# here as well.

**Comment by AathifMahir** [comment]
Anyone found a workaround for this issue?

**Comment by s3nt1n3l-hub** [comment]
@AathifMahir  - For us the issue was only present in an updated WinUI3 project (the new Reunion blank templates worked fine) so our work around was to install Reunion, create a new blank app and then copy the contents of the old project across. Obviously it unfortunately won't work for anyone that is having issues with new blank projects.

**Comment by Daniellled** [comment]
I am also seeing this issue but with the MAUI samples application. [149](https://github.com/dotnet/net6-mobile-samples/issues/149)

**Comment by micampbell** [comment]
Same here. I ran maui-check and everything looks good. Using Visual Studio 2019 Preview 16.11.0 Preview 1.0. Here are my details:

here's my error:
`
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at WeatherTwentyOne.WinUI.Program.Main(String[] args) in …\source\repos\WeatherTwentyOne\src\WeatherTwentyOne.WinUI3\obj\x64\Debug\net6.0-windows10.0.19041\Windows\WindowsApp.g.i.cs:line 26

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException
`

**Comment by poychang** [comment]
Launch the app via the packaging project. [#586](https://github.com/microsoft/ProjectReunion/issues/586#issuecomment-802098433)

![image](https://user-images.githubusercontent.com/4879879/120052759-70155280-c059-11eb-942e-bca54b516e3f.png)

**Comment by micampbell** [comment]
Thanks. I also found this video where he solves it: https://youtu.be/23PmntSTBIQ?t=430

**Comment by iMonZ** [comment]
> Launch the app via the packaging project. [#586](https://github.com/microsoft/ProjectReunion/issues/586#issuecomment-802098433)
> 
> ![image](https://user-images.githubusercontent.com/4879879/120052759-70155280-c059-11eb-942e-bca54b516e3f.png)

Thank you!
You saved my day

**Comment by Abdulrahmanelheyb** [comment]
![image](https://user-images.githubusercontent.com/45883300/142596210-6282b188-5d4a-4df9-b685-802cd70d0f91.png)
I get this error my pc is X64 hp 15-cc107nt
