### ISSUE TITLE
Unable to run blank template, error message 0x80040154

### ISSUE THREAD

**Issue by SoloWharf** [microsoft/ProjectReunion#586]
**Unable to run blank template, gives error message**

**Steps**

1. New project
2. Blank Window (WinUI in Desktop)
3. Run app (not package)

**I was expecting a blank window with a button on it**

**Version**

Windows 19042.867
VIsual Studio Community Edition 2019 Version 16.10.0 Preview 1.0
Project Reunion (0.5-prerelease)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| March 2021 Update (19042)            | Yes |
| May 2020 Update (19041)            |    |

**Additional info**

I installed VS2019 preview version, added the Project Reunion extension, created a new project using the Blank Window (WinUI in Desktop) template, then tried running the newly created project as is. I get this error message:

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at WinUI_Test_App.Program.Main(String[] args) in C:\Users\kimmy\Documents\GitHub\Testing\WinUI Test App\WinUI Test App\WinUI Test App\obj\x86\Debug\net5.0-windows10.0.19041.0\App.g.i.cs:line 26

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: Classe non enregistrée (0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by ecovio1** [comment]
maybe  /dup #583

**Comment by BenJKuhn** [comment]
This _might_ be the same issue as https://github.com/microsoft/ProjectReunion/issues/583, should be investigated together.

**Comment by DefaultRyan** [comment]
Is this for a C# or C++ project?

**Comment by SoloWharf** [comment]
C#

**Comment by BenJKuhn** [comment]
The class registrations for the WinUI WinRT types are registered as part of launching the app project. It's expected behavior that running the EXE outside of the package will cause it to not find WinUI & fail in this way.

**Comment by SoloWharf** [comment]
And the solution is....??

I'm running it from Visual Studio.

**Comment by riverar** [comment]
@SoloWharf You must launch your desktop app via the Windows Application Packaging project. Unpackaged desktop apps [are not supported yet](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#limitations-and-known-issues).
