### ISSUE TITLE
Error MSB4018 The "ReplaceMUXWinRTRegistrations" task failed unexpectedly

### ISSUE THREAD

**Issue by AndreMarschalek** [microsoft/ProjectReunion#594]
**Describe the bug**
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ReplaceMUXWinRTRegistrations" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'C:\Users\USER\.nuget\packages\microsoft.projectreunion.winui\0.5.0-prerelease\buildTransitive\LiftedWinRTClassRegistrations.xml'.
File name: 'C:\Users\USER\.nuget\packages\microsoft.projectreunion.winui\0.5.0-prerelease\buildTransitive\LiftedWinRTClassRegistrations.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at InlineCode.ReplaceMUXWinRTRegistrations.Execute() in c:\Users\Andre\AppData\Local\Temp\sw24uwpw.0.cs:line 116
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Downloader_Package	D:\VSTS\Source\Repos\Entertainment\Downloader\Downloader (Package)\build\Microsoft.WinUI.AppX.targets	45
```
"LiftedWinRTClassRegistrations.xml" does not exist in that path
[content.txt](https://github.com/microsoft/ProjectReunion/files/6157955/content.txt)

**Steps to reproduce the bug**
started from a "Win UI Desktop App" fresh created based on WinUI 3 Preview 4 and added WebView and other things 
following Project Reunion instructions removed the WinUI VS Extensions and did also a revert of WebView Component
after removal installed Project Reunion Visual Studio Extension
removed WinUI3 Preview4 NuGET Package from WinUI Desktop App and added Microsoft.ProjectReunion NuGET Package
clean Solution and build Solution

**Expected behavior**
no error message and Project should successfully compile 

**Screenshots**
n/a

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion 0.5.0-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
|20H2 (19042)            | Yes  |

**Additional context**
n/a

**Comment by huichen123** [comment]
Please replace Microsoft.WinUI.AppX.targets file in build folder of the packaging project with the one from Microsoft.ProjectReunion.WinUI package (under build folder).

**Comment by AndreMarschalek** [comment]
i found the Microsoft.WinUI.AppX.targets file in build folder of the packaging project (its the only content in this folder) but what do you mean with "the one from Microsoft.ProjectReunion.WinUI package (under build folder)." ?

**Comment by huichen123** [comment]
it's in your nuget cache. Usually it's under C:\Users\[username]\.nuget\packages\microsoft.projectreunion.winui\0.5.0-Prerelease\build

**Comment by AndreMarschalek** [comment]
this solved the problem and build was successful
thank you for your help!
